### ISSUE TITLE
Authenticity of checksum file can not be assured (14.10.0)

### ISSUE THREAD

**Issue by AlphaHydrae** [asdf-vm/asdf-nodejs#174]
There seems to be a download/checksum problem when installing the latest 14.10.0 version with asdf v0.8.0.

```
$> asdf install nodejs 14.10.0                                                           
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3838    0  3838    0     0  29459      0 --:--:-- --:--:-- --:--:-- 29523
Authenticity of checksum file can not be assured! Please be sure to check the README of asdf-nodejs in case you did not yet import the needed PGP keys. If you already did that then that is the point to become SUSPICIOUS! There must be a reason why this is failing. If you are installing an older NodeJS version you might need to import OpenPGP keys of previous release managers. Exiting.



$> bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
gpg: keyserver receive failed: No route to host
gpg: keyserver receive failed: No route to host
gpg: key 7434390BDBE9B9C5: public key "Colin Ihrig <cjihrig@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: keyserver receive failed: No route to host
gpg: keyserver receive failed: No route to host
gpg: key 09FE44734EB7990E: public key "Jeremiah Senkpiel <fishrock123@rocketmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: keyserver receive failed: No route to host
gpg: keyserver receive failed: No route to host
gpg: key C97EC7A07EDE3FC1: public key "keybase.io/jasnell <jasnell@keybase.io>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: keyserver receive failed: No route to host
gpg: keyserver receive failed: No route to host
gpg: key C273792F7D83545D: public key "Rod Vagg <rod@vagg.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: keyserver receive failed: No route to host
gpg: keyserver receive failed: No route to host
gpg: key E73BC641CC11F4C8: public key "Myles Borins <myles.borins@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: keyserver receive failed: No route to host
gpg: keyserver receive failed: No route to host
gpg: key B63B535A4C206CA9: public key "Evan Lucas <evanlucas@me.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: keyserver receive failed: No route to host
gpg: keyserver receive failed: No route to host
gpg: key 770F7A9A5AE15600: public key "Michaël Zasso (Targos) <targos@protonmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: keyserver receive failed: No route to host
gpg: keyserver receive failed: No route to host
gpg: key B01FBB92821C587A: public key "Gibson Fahnestock <gibfahn@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: keyserver receive failed: No route to host
gpg: keyserver receive failed: No route to host
gpg: key F07496B3EB3C1762: public key "Ruben Bridgewater <ruben@bridgewater.de>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: keyserver receive failed: No route to host
gpg: keyserver receive failed: No route to host
gpg: key D7062848A1AB005C: public key "Beth Griggs <Bethany.Griggs@uk.ibm.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: keyserver receive failed: No route to host
gpg: keyserver receive failed: No route to host
gpg: key F13993A75599653C: public key "Shelley Vohr (security is major key) <shelley.vohr@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1



$> asdf install nodejs 14.10.0                                                           
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3838    0  3838    0     0  29459      0 --:--:-- --:--:-- --:--:-- 29523
Authenticity of checksum file can not be assured! Please be sure to check the README of asdf-nodejs in case you did not yet import the needed PGP keys. If you already did that then that is the point to become SUSPICIOUS! There must be a reason why this is failing. If you are installing an older NodeJS version you might need to import OpenPGP keys of previous release managers. Exiting.
```

**Comment by beardedeagle** [comment]
Same issue as above.

**Comment by XX-NF-XX** [comment]
PR #173 should resolve this issue

**Comment by Stratus3D** [comment]
#173 has been merged.

**Comment by abumalick** [comment]
I still get the issue after upgrading the plugin

``` bash
$ cat ~/.asdf/plugins/nodejs/bin/import-release-team-keyring | grep C82FA3AE1CBEDC6BE46B9360C43CEC45C17AB93C
      C82FA3AE1CBEDC6BE46B9360C43CEC45C17AB93C \
$ asdf install nodejs 14.10.0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--    100  3838    0  3838    0     0  17366      0 --:--:-- --:--:-- --:--:-- 17366
Authenticity of checksum file can not be assured! Please be sure to check the README of asdf-nodejs in case you did not yet import the needed PGP keys. If you already did that then that is the point to become SUSPICIOUS! There must be a reason why this is failing. If you are installing an older NodeJS version you might need to import OpenPGP keys of previous release managers. Exiting.
```

any idea?

**Comment by abumalick** [comment]
oh, got it.

We need to reimport the keys

```bash
bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
```

**Comment by abumalick** [comment]
Thanks for the fix @XX-NF-XX

**Comment by crcastle** [comment]
If anyone else bumps into this, it took me a few minutes to realize I had to run the following commands in this order:

```shell
asdf plugin update nodejs
bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
asdf install nodejs 14.10.0
```

The first update command was the one I was missing.

**Comment by npearson72** [comment]
I'm still getting the `gpg: keyserver receive failed: No route to host` error after running:

```
asdf plugin update nodejs
bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
```

Any ideas?
