### ISSUE TITLE
Global installs not being found in npm@7

### ISSUE THREAD

**Issue by jonatan-ivanov** [asdf-vm/asdf-nodejs#227]
Globally installed packages can't be executed and the command fails with `command not found`.
Workaround: `export PATH="$PATH:$(asdf where nodejs)/.npm/bin"` (though I guess this won't work with version change)

**Comment by augustobmoura** [comment]
Try running `asdf rehism nodejs` after `npm install -g`, `.npm/bin` should not be in the path (not without workarounds) this is not how asdf works internally, the problem with adding `$(asdf where nodejs)` to PATH is that it can change from directory to directory. Instead asdf creates a shim for every executable in .npm/bin so that it can point to the correct nodejs version

This is caused by a [npm@7 regression](https://github.com/npm/cli/issues/2692), as of now we will need to manually run `asdf reshim nodejs` after every global install, I'm currently researching a way of not relying in .hooks to auto reshim

**Comment by augustobmoura** [comment]
Okay, so I pushed a new mechanism for auto-reshimming that works by wrapping the npm command and only reshimming when necessary. Instead of relying on npm `node_modules/.hooks`.

@jonatan-ivanov, can you update your asdf-nodejs and test if everything is working as intended?

**Comment by jonatan-ivanov** [comment]
@augustobmoura Thanks for looking into this. I uninstalled and installed a package, both times I see the message: `Reshimming asdf nodejs...` and this works now, thank you! :)

**Comment by igoracmelo** [comment]
I installed asdf using AUR and I'm still having this issue, even after reopening my terminal.

https://user-images.githubusercontent.com/85039990/149785975-92c855ee-3cc2-4fd6-a236-4042722447ba.mp4

**Comment by rroslaniec** [comment]
same here

**Comment by iloveitaly** [comment]
running into this as well, I wonder if it has something to do with the global vs local asdf nodejs version. If I have more time to investigate further, I'll reach out.

**Comment by TamasBarta** [comment]
@iloveitaly, if the global one was used to install the npm package instead of the asdf managed version, I believe you should still get the command in the path, but not managed by asdf. I start to believe that npm itself is faulty, because I tried setting asdf's nodejs to system, and I just have no way of getting any command to work. The workaround mentioned here also doesn't work for me, because that directory has no commands either. (`export PATH="$PATH:$(asdf where nodejs)/.npm/bin"`) I'm confused.

**Comment by mcandre** [comment]
I don't understand why this issue is closed. asdf-nodejs breaks executables installed via `npm install -g <package>`.

**Comment by noizu** [comment]
This might help:

1. Ensure the correct version of your nodejs shim is set.
```
asdf where nodejs
#> /home/keith/.asdf/installs/nodejs/10.24.1
```

2. Ensure your npm shim is configured correctly and it's `npm root- g` folder matches `$(asdf where nodejs)/lib/node_modules`

```
which npm
# /home/keith/.asdf/shims/npm

npm root -g
#> /home/keith/.asdf/installs/nodejs/10.24.1/lib/node_modules
```

3. Install global package. `npm install -g ${package}`

4. Verify executable was bin placed under `$(asdf where nodejs)/bin` 

**If it is bin placed make sure it's executable and reshim otherwise try deleting the shim folder and reshiming. `asdf reshim nodejs**

5. If executable was not bin placed find the file under `$(asdf where nodejs)/lib/node_modules` 

```
find $(asdf where nodejs)/lib/node_modules -type f -name lessc
# /home/keith/.asdf/installs/nodejs/10.24.1/lib/node_modules/lessc/node_modules/less/bin/lessc
```

6. and symlink to target node versions bin folder. 
```
ln -s $(asdf where nodejs)/lib/node_modules/lessc/node_modules/less/bin/lessc $(asdf where nodejs)/bin/
```

7. once added run `asdf reshim nodejs` and hopefully things work as expected. 
You will need to install the global package with npm for each asdf node version you wish to use it with. 


----
If you installed globally add a symlink to the bin folder of the nodejs versions you wish to use the global package with and reshimming should work as expected as long as the package is supported by that nodejs version. There may be path issues however.

**Comment by josias-r** [comment]
I just came across this closed issue, because I had the same issue, a reshim fixed it. Might this auto reshimming be broken in asdf 0.16.x?

**Comment by chrisskilton** [comment]
ran into this too. reshim fixed 🙏
