### ISSUE TITLE
Install broken on OS X

### ISSUE THREAD

**Issue by scottdavis** [asdf-vm/asdf-nodejs#29]
`$ asdf install nodejs 7.5.0`
```
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
```

**Comment by bobishh** [comment]
+1 :-(
Error above related to usage of "--directory" argument passed to mktemp utility in install script

Theres' also linux-specific usage of sort in install script, broken since [this commit](https://github.com/asdf-vm/asdf-nodejs/commit/c213d9c20ec0f087cbecdf4998ebbb8ca6f0e16f)

**Comment by scottdavis** [comment]
Seems to be still broken even after yesterdays commits 
```
$ asdf install nodejs 7.5.0
sort: invalid option -- V
Try `sort --help' for more information.
7.5.0 did not provide signed checksums or support for them has not been implemented and NODEJS_CHECK_SIGNATURES=strict is set. Exiting.
```

**Comment by HashNuke** [comment]
@bobishh @scottdavis thanks for reporting ~! I'll look into it in a few hours after work and fix it.

**Comment by cdegroot** [comment]
sort -V is broken, "fixed" by installing coreutils and s/sort/gsort/. Next up then come some more incompatibilities:

```
$ asdf install node 4.8.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4080    0  4080    0     0  45581      0 --:--:-- --:--:-- --:--:-- 45842
gpg: Signature made Tue Feb 21 20:41:01 2017 EST using RSA key ID 0B5CA946
gpg: Good signature from "Myles Borins <myles.borins@gmail.com>" [unknown]
gpg:                 aka "Myles Borins <mborins@google.com>" [unknown]
gpg:                 aka "Myles Borins <mylesborins@google.com>" [unknown]
gpg:                 aka "Myles Borins (Not used after January 2017) <mborins@us.ibm.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: C4F0 DFFF 4E8C 1A82 3640  9D08 E73B C641 CC11 F4C8
     Subkey fingerprint: 0EFF E1BC EFD9 C84E 3D09  8152 933B 01F4 0B5C A946
uname: illegal option -- -
usage: uname [-amnprsv]
uname: illegal option -- -
usage: uname [-amnprsv]
uname: illegal option -- -
usage: uname [-amnprsv]
uname: illegal option -- -
usage: uname [-amnprsv]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6162    0  6162    0     0  25385      0 --:--:-- --:--:-- --:--:-- 25358
uname: illegal option -- -
usage: uname [-amnprsv]
uname: illegal option -- -
usage: uname [-amnprsv]
/Users/cees/.asdf/plugins/node/bin/install: line 210: sha256sum: command not found
Authenticity of package archive can not be assured. Exiting.
```

**Comment by cdegroot** [comment]
Patchwork to make it work on MacOS:
```
$ git diff
diff --git a/bin/install b/bin/install
index 1e16a40..d15bfa6 100755
--- a/bin/install
+++ b/bin/install
@@ -71,7 +71,7 @@ construct_configure_options() {

 get_nodejs_machine_hardware_name() {
   local machine_hardware_name
-  machine_hardware_name="$(uname --machine)"
+  machine_hardware_name="$(uname -m)"

   case "$machine_hardware_name" in
     'x86_64') local cpu_type="x64";;
@@ -98,7 +98,7 @@ get_archive_file_name() {
   local pkg_name

   if [ "$install_type" = "version" ]; then
-    pkg_name="node-v${version}-$(uname --kernel-name | tr '[:upper:]' '[:lower:]')-$(get_nodejs_machine_hardware_name)"
+    pkg_name="node-v${version}-$(uname -s | tr '[:upper:]' '[:lower:]')-$(get_nodejs_machine_hardware_name)"
   else
     pkg_name="${version}"
   fi
@@ -207,7 +207,7 @@ verify_archive() {

     (
       cd "${tmp_download_dir}"
-      if ! sha256sum --check <(grep "\s$archive_file_name$" "${authentic_checksum_file}"); then
+      if ! shasum -a 256 --check <(grep "\s$archive_file_name$" "${authentic_checksum_file}"); then
         echo "Authenticity of package archive can not be assured. Exiting." >&2
         exit 1
       fi
@@ -218,7 +218,7 @@ verify_archive() {

 verlte() {
   ## https://stackoverflow.com/questions/4023830/how-compare-two-strings-in-dot-separated-version-format-in-bash/4024263#4024263
-  [  "$1" = "$(echo -e "$1\n$2" | sort -V | head -n1)" ]
+  [  "$1" = "$(echo -e "$1\n$2" | gsort -V | head -n1)" ]
 }
```

The `uname` diffs are portable. `shasum -a 256` should work on Linux as well. Leaves `sort`, which probably requires a little switch and docs that state that on MacOS, `brew install coreutils` is a prerequisite.

**Comment by HashNuke** [comment]
Thank you @cdegroot and @ZuraGuerra. This is fixed in #30. Closing issue.

**Comment by jeffcole** [comment]
This is still broken for me. I looks like maybe it's downloading the version but not installing it:
```
$ asdf install nodejs 7.5.0 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4756    0  4756    0     0  30836      0 --:--:-- --:--:-- --:--:-- 30883

$ 
```

**Comment by ZuraGuerra** [comment]
@jeffcole Did you do the OpenGPG keys step?

**Comment by jeffcole** [comment]
@ZuraGuerra thanks for pointing me to that. Looks like we might still be missing a dependency step in the instructions:

```
❯ brew install coreutils 
==> ...
==> Summary
🍺  /usr/local/Cellar/coreutils/8.26: 430 files, 8.5M

❯ asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
Cloning into '/Users/jeff/.asdf/plugins/nodejs'...
...
Resolving deltas: 100% (90/90), done.

❯ bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring 
/Users/jeff/.asdf/plugins/nodejs/bin/import-release-team-keyring: line 7: gpg: command not found
```

**Comment by ZuraGuerra** [comment]
[It's stated in the ReadMe](https://github.com/asdf-vm/asdf-nodejs/blob/master/README.md) right now:

"Requires gpg to be available during package installs."

**Comment by jeffcole** [comment]
@ZuraGuerra I see now, sorry and thanks!

**Comment by ZuraGuerra** [comment]
Don't worry. Hope it works now! :)

**Comment by lowski** [comment]
Right now it's saying `/Users/lucas/.asdf/plugins/nodejs/bin/install: line 223: gsort: command not found`.

Why another sorting lib is needed? I remember using this plugin some time ago and it was working fine without external deps.

**Comment by ZuraGuerra** [comment]
@lowski Did you install the GNU Core Utils dep? `brew install coreutils`
Because of the addition of the Node binary validation, we had to modify the installation script.

**Comment by lowski** [comment]
@ZuraGuerra no I haven't installed it.

I don't know how I miss it in the `README`. Thanks, it's working now.

**Comment by stevelove** [comment]
Looks like the change to `shasum` caused installation to start failing on CentOS. It may be worth documenting this command can be obtained through: `yum install perl-Digest-SHA`.

**Comment by alejandromangione** [comment]
to resolve it, use (OSx 10.13): 
`brew install gpg`
