### ISSUE TITLE
node-build: definition not found: 16.15.0

### ISSUE THREAD

**Issue by lestephane** [asdf-vm/asdf-nodejs#297]
If someone can tell me where to add the definition, I'll gladly file a PR.

But, should there not have a fallback mechanism to the immediately preceding version
when someone tries to install an lts alias so new that there is no definition for it yet? 

```
$ asdf direnv local nodejs lts
▶ asdf plugin-add nodejs # ...  Plugin named nodejs already added
✔️
▶ asdf install nodejs lts # ...  Installing alias lts as 16.15.0
Trying to update node-build... ok
node-build: definition not found: 16.15.0
Could not install version 16.15.0
❗️ Failed with status 1
```

**Comment by fschoenfeldt** [comment]
I told my colleague "asdf is way easier than node installer" and stumbled upon this error on setting it up on her pc. 

thanks for reporting, now using a pinned version.

**Comment by AlJohri** [comment]
Just got the same error:

```
❯ asdf version
v0.10.0-77fd510

❯ git -C ~/.asdf/plugins/nodejs show
commit f9957f3f256ebbb3fdeebcaed5082ad305222be6 (HEAD -> master, origin/master, origin/HEAD)
Merge: 364c078 1365f37
Author: Augusto Moura <me@augustomoura.com>
Date:   Mon Mar 14 15:03:28 2022 -0300

    Merge pull request #292 from burnettk/filter-list-all-to-ensure-we-can-install-them

    if a version is not installable via node-build, make sure it is not in list-all

❯ asdf install nodejs lts-gallium
Installing alias lts-gallium as 16.15.0
Trying to update node-build... ok
node-build: definition not found: 16.15.0
Could not install version 16.15.0
```

**Comment by AlJohri** [comment]
Here's the PR waiting to be merged: https://github.com/nodenv/node-build/pull/750

**Comment by AlJohri** [comment]
Looks like this issue occurred before as well when version `16.14.1` was released: https://github.com/asdf-vm/asdf-nodejs/issues/294

**Comment by augustobmoura** [comment]
It's the same problem that I talked on https://github.com/asdf-vm/asdf-nodejs/issues/294#issuecomment-1068702036. I will try to push a better solution today

**Comment by AlJohri** [comment]
(for the record, looks like this same issue occurred here https://github.com/asdf-vm/asdf-nodejs/issues/283 on release of 16.14.0. it was released on 2/8 and the user opened the issue on 2/9)

Thank you for looking into it @augustobmoura!!

**Comment by augustobmoura** [comment]
Should be fixed on master now. We can't install install 16.15 until https://github.com/nodenv/node-build/pull/750 is merged. What the PR does is install the previous lts when resolving aliases, in this case it's the version 16.14.2

**Comment by sagarpadiya6** [comment]
@augustobmoura  its still not fixed. I am still. facing the same issue

**Comment by augustobmoura** [comment]
> @augustobmoura its still not fixed. I am still. facing the same issue

Did you update, both `asdf` and the `asdf-node` plugin?
Try running:
``` bash
asdf update && asdf plugin-update --all
```

**Comment by codethief** [comment]
I just ran into this issue today: Using a freshly installed asdf 0.11.3, I run `asdf plugin add nodejs` and afterwards attempt to `asdf install` the `lts-gallium` that's specified in my `.tool-versions`. This yields:

```
$ asdf install
Trying to update node-build...
 ok
node-build: definition not found: 16
```

For lts-hydrogen / Node v18 I get the same result.

**Comment by jdxcode** [comment]
they got rid of the ability to use aliases like lts-hydrogen in `.tool-versions` files in #348 as this wasn't functionality they intended to support

**Comment by joshvazquez-amzn** [comment]
I also had this issue but I'm not using `.tool-versions`, just installing for the first time. If you run `asdf list-all nodejs`, 16 is not there (nor 18). So I did `asdf install nodejs 18.16.0` which worked.

**Comment by augustobmoura** [comment]
> I just ran into this issue today: Using a freshly installed asdf 0.11.3, I run `asdf plugin add nodejs` and afterwards attempt to `asdf install` the `lts-gallium` that's specified in my `.tool-versions`. This yields:
> 
> ```
> $ asdf install
> Trying to update node-build...
>  ok
> node-build: definition not found: 16
> ```
> 
> For lts-hydrogen (Node v18) I get the same result. For now I have hard-coded the version number in my `.toolbox-versions` and this seems to work.

> they got rid of the ability to use aliases like `lts-hydrogen` in `.tool-versions` files in #348 as this wasn't functionality they intended to support

Partial versions and codenames were never a feature, it working was unintentional. For using it consider pinning the version on `.tool-version` file and automating it update or change to a `legacy_file_version` (`.node-version`, `.nvmrc`), more info on the [README](https://github.com/asdf-vm/asdf-nodejs#partial-and-codename-versions)



> If you run `asdf list-all nodejs`, 16 is not there (nor 18). So I did `asdf install nodejs 18.16.0` which worked.

The old install command will not work, but `asdf-core` supports the `latest:<version>` prefix. You can install the latest 16 by running `asdf install nodejs latest:16`
